### ISSUE TITLE
State management

### ISSUE THREAD

**Issue by arsley** [kinc-shinshu/smaT-api#11]
Client側でのstate管理をAPIサーバー側へ委託する。
仕様は逐次コメントで。

**Comment by bieshan** [comment]
## Endpoint

#### `GET /questions/:question_id`

- `:question_id` : `Question.id`に相当

問題IDで個別な問題とrelustを持った問題の数を取得したい。

**Comment by bieshan** [comment]
#### `GET /exam/room_number`

- `room_number` : 前仕様のroom_idに相当

受けるべき問題の総数と問題ID一覧とrelustを持った問題の数を教えて欲しい。

**Comment by yoidea** [comment]
# 教師側クライアント
`ルーム`と`問題`のルーティングが実現できれば、現状のStateを移管できそう。
`room_id`については、`room_number`を使うほうが適切なのかも。

## ルーム
`POST /rooms`: ルーム開設
`DELETE /rooms/:id` or `PATCH /rooms/:id`: ルーム閉鎖

## 問題
`GET /rooms/:room_id/questions`: 問題一覧取得
`GET /rooms/:room_id/questions/:id`: 問題個別取得
`POST /rooms/:room_id/questions`: 問題追加
`DELETE /rooms/:room_id/questions/:id`: 問題削除

## 統計
うーん、わからん
`GET /rooms/:room_id/questions/:question_id/results`

**Comment by assly** [comment]
コメントありがとう。
ただ`Exam`テーブルと`Question`テーブルおよびその関連付けについての話は概ね完結している（APIのエンドポイントが定まればそれを使わせるだけ）ので別に重要ではなくて、**クライアント側の`State`をどう簡略化するか**ということが主題なので、例えば次のようなことを教えて欲しい。

- クライアント側で利用している`State`の現状
  - 現状を知れれば、それに沿った設計ができる
  - 個人的には`State`テーブルのようなものを作って**各クライアントが持つ、ページ間で引き継ぎたい情報**をすべてAPIに任せるようなものだと思っていた（下部にテーブルの仮案）
- 改善することでどのようなことが楽になるか
  - 単にコードの記述量を減らすことに意味はない（と思っている）ので、APIサーバー側に*とある*処理を任せることでどのような利点があるか、簡単でいいので理由を知りたい
  - 「ページ間での`State`管理が*面倒*」とかじゃなく、「`navigator.state`(?)で管理させようとするとコーディング時にミスを犯しやすい」のように客観的にだと理解しやすいです...

私が現状を把握しきれていないということが大きいので、どうかよろしくお願いします。

---

`State`

`client_id (VARCHAR)`|`q_id (VARCHAR)`|`judge (VARCHAR)`|`challenge (VARCHAR)`
-|-|-|-
`Y2xpZW50X2lkMQ==`|`1`|`0`|`1`
`Y2xpZW50X2lkMg==`|`1,2`|`0,0`|`1,2`
`cGVyc29uIG5hbWU=`|`1,2,3`|`0,0,1`|`1,2,5`
`d2hvIHlvdSBhcmU=`|`1,2,3,4`|`0,0,1,0,`|`1,2,5,4`

- `client_id` : Room入室時に端末を識別するために用いる一時的なBase64（被らないならなんでもOK）テキスト
  - 接続している生徒を識別する手段が現在ない
- 解答するたびに`UPDATE`する
- 解答送信後は`DELETE`する

**Comment by yoidea** [comment]
@assly 

少し考えてみた結果、教師側クライアントに関してはそれほど開放したいStateが多くないので、
> 各クライアントが持つ、ページ間で引き継ぎたい情報をすべてAPIに任せる

必要はなさそう。

## 現状
親コンポーネントで問題一覧の情報を管理しているため、追加・編集を行うには子コンポーネントから親のStateを更新する必要がある（Reactの設計思想として良くないのでは？と思っている）。

🗑️: Stateを開放したい
🔵: 必要なState

### App.js（親）
🗑️`questions[]`: 問題一覧

### Top.js（一覧）
🗑️`questions[]`: 親から受け取る

開放することで親から受け取る必要と親を更新する必要がなくなる。新しい問題を追加するたび通信する必要があるが、データの整合性が保証できる（必要性は無視して、２人の先生が同時編集みたいなことが可能になると思う）。

### Edit.js（編集）
🔵`timer`: setTimeout()
🔵`input`: 入力テキスト保持
🔵`output`: 変換後文字列出力

画面の振る舞いに直接関係するものばかりなので開放不可と思われる。

### Done.js（完了）
🗑️`id`: ルームID表示
🔵`progress`:  プログレス計算
🔵`barShow`: プログレスバー表示・非表示

## 変更案

### App.js（親）
`id`: ルームID

ルームIDを最初に取得して、子コンポーネントに受け渡す。ルームIDは途中で変更されることがないのでReactの設計思想に従ったpropsの受け渡しが実現できると思う。

### Top.js（一覧）
一覧画面が呼び出されるたびFetchして表示する。

### Edit.js（編集）
`timer`: setTimeout()
`input`: 入力テキスト保持
`output`: 変換後文字列出力

### Done.js（完了）
`progress`:  プログレス計算
`barShow`: プログレスバー表示・非表示

**Comment by arsley** [comment]
## 実装予定

```
GET /v1/room/:room_id/questions     v1/room#questions_index
GET /v1/room/:room_id/questions/:id    v1/room#questions_show
#=> ここでの:idは1, 2 ... であり、DBにおけるIDではない
#=> Teacher.first.exams.first.questions[0] とかできる

GET /v1/states/:client_id    v1/states#show
POST /v1/states/:client_id    v1/states#update
```
