### ISSUE TITLE
ルームの退室機能も入れた方が良さそう？

### ISSUE THREAD

**Issue by bieshan** [kinc-shinshu/smaT-api#5]
APIサーバーじゃなくても他のところで実現できます。
ただAPIサーバーにルームの"入室"機能ついてるから、"退室"機能も同じ所に入れたくない？

**Comment by yoidea** [comment]
確かに明示的に退室できてもいいかも。
とりあえず機能として、createだけじゃなくてindex, destroyもできるようにしておくか。
